### ISSUE TITLE
CJSX not supported

### ISSUE THREAD

**Issue by ScreenDriver** [AtomLinter/linter-coffeelint#34]
I use CoffeeScript with the React library. So I use CJSX files. Unfortunately I get following error:

![screenshot](https://cloud.githubusercontent.com/assets/149248/7468150/2c423776-f305-11e4-8d38-2a9357b58c0e.png)

**Comment by AsaAyers** [comment]
It isn't supported directly. You need to add `coffee-react-transform` to your CoffeeLint config. We're currently having a problem [loading transforms](https://github.com/AtomLinter/linter-coffeelint/issues/25). There is a workaround in the issue.

**Comment by AsaAyers** [comment]
Fixed. See https://github.com/AtomLinter/linter-coffeelint/issues/25#issuecomment-99122300

**Comment by ScreenDriver** [comment]
Thank you. I updated to `v0.2.3` but the error still occurs.

**Comment by AsaAyers** [comment]
Did you also install and configure coffee-react-transform? I didn't add CJX support directly, I only fixed the bug that prevented people from using transforms like coffee-react-transform

**Comment by ScreenDriver** [comment]
:+1: 
it works now :sunglasses:
